### ISSUE TITLE
How LightGBM works?

### ISSUE THREAD

**Issue by kamil-kaczmarek** [minerva-ml/open-solution-home-credit#13]
* how it works?
* which parameters are important and why?
* rules of thumb for grid search

**Comment by mlisovyi** [comment]
[This](https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters-Tuning.rst) general lightgbm doc and [these](https://github.com/Microsoft/LightGBM/issues/695) instructions in one of the issues might be helpful

**Comment by kamil-kaczmarek** [comment]
done, follow up with @buus2
