### ISSUE TITLE
write solution-1 description on wiki

### ISSUE THREAD

**Issue by kamil-kaczmarek** [minerva-ml/open-solution-home-credit#27]
Write here: [LightGBM-and-basic-features](https://github.com/minerva-ml/open-solution-home-credit/wiki/LightGBM-and-basic-features)

Use [DSB wiki](https://github.com/minerva-ml/open-solution-data-science-bowl-2018/wiki) as a reference.

**Comment by kstrzala** [comment]
@kamil-kaczmarek  permission needed

**Comment by kamil-kaczmarek** [comment]
done
